apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: cct8qjshj-python 
  janus-idp.io/tekton: cct8qjshj-python
  backstage.io/kubernetes-id: cct8qjshj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cct8qjshj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml